pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/nodejs
        tags: 12.11.1-alpine
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
